### PR TITLE
optimising "from_scanpy" function

### PR DESCRIPTION
**Pull request by kcArtemis**
**PR Checklist**

-   [x] Referenced issue is linked [isse: 438](https://github.com/theislab/pertpy/issues/438)
-   [ ] If you've fixed a bug or added code that should be tested, add tests!
-   [ ] Documentation in `docs` is updated

**Description of changes**
Have removed "for" loop for optimising and even used set operations for curation of _covariate_obs_ list.

**Technical details**
Created a temp_df variable for storing the groupby generated data frame and then filtered the columns of the newly generated data frame to remove inconsistent covariate_obs.
Also `covariate_obs += [i for i in sample_identifier if i not in covariate_obs]` is changed into `covariate_obs = list(set(covariate_obs + sample_identifier))`
**Additional context**
Needed a test database where I can compare the speed.  I used a very small dataset, thus can't be tested properly.

### CODE REVIEW

**Comment by Zethson** [comment]
Thanks!

1. It needs to be tested properly. We cannot merge code that has not been tested. You will need to create a proper AnnData object then.
2. Please create a quick reproducible script that shows how you timed it.
3. Show the before and after numbers.
4. No uncommented code please. It has to be removed.

This task probably takes a tiny bit more time so don't be confused if you're working on this for a bit longer.

**Comment by kcArtemis** [comment]
```import time
import pandas as pd
import scanpy as sc
import pertpy as pt

adata = pt.dt.haber_2017_regions() #Reading the dataset
sccoda = pt.tl.Sccoda()

sample_identifier = "batch"
cell_type_identifier = "cell_label"
covariate_df = None
covariate_obs = ["condition"]
covariate_uns = None

#Updated version

if isinstance(sample_identifier, str):
    sample_identifier = [sample_identifier]

start = time.time() #Starting the timer
if covariate_obs:
    covariate_obs = list(set(covariate_obs + sample_identifier)) #Unique element list
else:
    covariate_obs = sample_identifier  # type: ignore
end = time.time()
time1 = end-start #Time taken to run the above code

# join sample identifiers
if isinstance(sample_identifier, list):
    adata.obs["scCODA_sample_id"] = adata.obs[sample_identifier].agg("-".join, axis=1)
    sample_identifier = "scCODA_sample_id"

# get cell type counts
groups = adata.obs.value_counts([sample_identifier, cell_type_identifier])
count_data = groups.unstack(level=cell_type_identifier)
count_data = count_data.fillna(0)

# get covariates from different sources
covariate_df_ = pd.DataFrame(index=count_data.index)

if covariate_df is None and covariate_obs is None and covariate_uns is None:
    print("No covariate information specified!")

if covariate_uns is not None:
    covariate_df_uns = pd.DataFrame(adata.uns[covariate_uns])
    covariate_df_ = pd.concat((covariate_df_, covariate_df_uns), axis=1)

start = time.time()
if covariate_obs is not None:
    temp_df = adata.obs.groupby(sample_identifier).nunique()[covariate_obs] # grouped dataset with columns from covariate_obs and rows are the unique values of sample across covariate_obs
    covariate_obs = temp_df.columns[temp_df.nunique() == 1] # columsn which will have values other than 1 will be removed
    covariate_df_obs = adata.obs.groupby(sample_identifier).first()[covariate_obs]
    covariate_df_ = pd.concat((covariate_df_, covariate_df_obs), axis=1)
end = time.time()
time2 = end-start #Time taken to run the above code
print(f"Updated code takes {time1+time2} seconds")
print("The datasete will look like: ")
print(covariate_df_)


#Older version
adata = pt.dt.haber_2017_regions()
adata = sc.read_h5ad("haber_count.h5ad")
sccoda = pt.tl.Sccoda()

sample_identifier = "batch"
cell_type_identifier = "cell_label"
covariate_df = None
covariate_obs = ["condition"]
covariate_uns = None


if isinstance(sample_identifier, str):
    sample_identifier = [sample_identifier]

start = time.time()
if covariate_obs is not None:
    covariate_obs += [i for i in sample_identifier if i not in covariate_obs]
else:
    covariate_obs = sample_identifier  # type: ignore
end = time.time()
time1 = end-start

# join sample identifiers
if isinstance(sample_identifier, list):
    adata.obs["scCODA_sample_id"] = adata.obs[sample_identifier].agg("-".join, axis=1)
    sample_identifier = "scCODA_sample_id"

# get cell type counts
groups = adata.obs.value_counts([sample_identifier, cell_type_identifier])
count_data = groups.unstack(level=cell_type_identifier)
count_data = count_data.fillna(0)

# get covariates from different sources
covariate_df_ = pd.DataFrame(index=count_data.index)

if covariate_df is None and covariate_obs is None and covariate_uns is None:
    print("No covariate information specified!")

if covariate_uns is not None:
    covariate_df_uns = pd.DataFrame(adata.uns[covariate_uns])
    covariate_df_ = pd.concat((covariate_df_, covariate_df_uns), axis=1)

start = time.time()
if covariate_obs is not None:
    for c in covariate_obs:
        if any(adata.obs.groupby(sample_identifier).nunique()[c] != 1):
            print(f"Covariate {c} has non-unique values! Skipping...")
            covariate_obs.remove(c)

    covariate_df_obs = adata.obs.groupby(sample_identifier).first()[covariate_obs]
    covariate_df_ = pd.concat((covariate_df_, covariate_df_obs), axis=1)
end = time.time()
time2 = end-start
print(f"old code takes {time1+time2} seconds")
print("The datasete will look like: ")
print(covariate_df_)```

script for testing the execution time and the output code for updated and older version.

**Comment by Zethson** [comment]
Good! Now, please use this script to 

1. The behavior of before and after is NOT allowed to change. Consider all possible `if` cases. Test this well.
2. The new solution must run ~10-100 times faster.
3. Use https://github.com/nschloe/tuna to profile code if necessary
4. Don't forget to update the code in this PR with your new solution then :)

**Comment by Zethson** [comment]
Superseded by https://github.com/theislab/pertpy/pull/473

**Pull request closed without merging**
